/**
 * This file is part of Traintastic,
 * see <https://github.com/traintastic/traintastic>.
 *
 * Copyright (C) 2025 Reinder Feenstra
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#ifndef TRAINTASTIC_SIMULATOR_COLOR_HPP
#define TRAINTASTIC_SIMULATOR_COLOR_HPP

// X11 colors:
enum class Color
{
  AliceBlue,
  AntiqueWhite,
  Aqua,
  Aquamarine,
  Azure,
  Beige,
  Bisque,
  Black,
  BlanchedAlmond,
  Blue,
  BlueViolet,
  Brown,
  Burlywood,
  CadetBlue,
  Chartreuse,
  Chocolate,
  Coral,
  CornflowerBlue,
  Cornsilk,
  Crimson,
  Cyan,
  DarkBlue,
  DarkCyan,
  DarkGoldenrod,
  DarkGray,
  DarkGreen,
  DarkKhaki,
  DarkMagenta,
  DarkOliveGreen,
  DarkOrange,
  DarkOrchid,
  DarkRed,
  DarkSalmon,
  DarkSeaGreen,
  DarkSlateBlue,
  DarkSlateGray,
  DarkTurquoise,
  DarkViolet,
  DeepPink,
  DeepSkyBlue,
  DimGray,
  DodgerBlue,
  Firebrick,
  FloralWhite,
  ForestGreen,
  Fuchsia,
  Gainsboro,
  GhostWhite,
  Gold,
  Goldenrod,
  Gray,
  WebGray,
  Green,
  WebGreen,
  GreenYellow,
  Honeydew,
  HotPink,
  IndianRed,
  Indigo,
  Ivory,
  Khaki,
  Lavender,
  LavenderBlush,
  LawnGreen,
  LemonChiffon,
  LightBlue,
  LightCoral,
  LightCyan,
  LightGoldenrod,
  LightGray,
  LightGreen,
  LightPink,
  LightSalmon,
  LightSeaGreen,
  LightSkyBlue,
  LightSlateGray,
  LightSteelBlue,
  LightYellow,
  Lime,
  LimeGreen,
  Linen,
  Magenta,
  Maroon,
  WebMaroon,
  MediumAquamarine,
  MediumBlue,
  MediumOrchid,
  MediumPurple,
  MediumSeaGreen,
  MediumSlateBlue,
  MediumSpringGreen,
  MediumTurquoise,
  MediumVioletRed,
  MidnightBlue,
  MintCream,
  MistyRose,
  Moccasin,
  NavajoWhite,
  NavyBlue,
  OldLace,
  Olive,
  OliveDrab,
  Orange,
  OrangeRed,
  Orchid,
  PaleGoldenrod,
  PaleGreen,
  PaleTurquoise,
  PaleVioletRed,
  PapayaWhip,
  PeachPuff,
  Peru,
  Pink,
  Plum,
  PowderBlue,
  Purple,
  WebPurple,
  RebeccaPurple,
  Red,
  RosyBrown,
  RoyalBlue,
  Saddlebrown,
  Salmon,
  SandyBrown,
  SeaGreen,
  Seashell,
  Sienna,
  Silver,
  SkyBlue,
  SlateBlue,
  SlateGray,
  Snow,
  SpringGreen,
  SteelBlue,
  Tan,
  Teal,
  Thistle,
  Tomato,
  Turquoise,
  Violet,
  Wheat,
  White,
  WhiteSmoke,
  Yellow,
  YellowGreen,
};

#endif
