
if(DEFINED ENV{GITHUB_ACTIONS})
  if($ENV{GITHUB_REF_TYPE} MATCHES "branch")

    set(TRAINTASTIC_CODENAME "$ENV{CI_REF_NAME_SLUG}-$ENV{GITHUB_RUN_NUMBER}-$ENV{CI_SHA_SHORT}")

    if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
      execute_process(COMMAND lsb_release -i -s OUTPUT_VARIABLE LSB_RELEASE_ID)
      execute_process(COMMAND lsb_release -c -s OUTPUT_VARIABLE LSB_RELEASE_CODENAME)

      set(DEBIAN_PACKAGE_VERSION_EXTRA "~${LSB_RELEASE_ID}~${LSB_RELEASE_CODENAME}~$ENV{CI_REF_NAME_SLUG}~$ENV{GITHUB_RUN_NUMBER}~$ENV{CI_SHA_SHORT}")
    endif()
  endif()
endif()
